server.port=${PORT:8080}
spring.application.name=controle-qualidade-api
spring.datasource.url=${DATABASE_URL:jdbc:h2:mem:testdb}
spring.datasource.username=${DATABASE_USERNAME:sa}
spring.datasource.password=${DATABASE_PASSWORD:}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.h2.console.enabled=true
spring.jackson.serialization.write-dates-as-timestamps=false
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
jwt.secret=278f3a03c00ed38915702b00ecb8156a76063e1ca5fc5355952133fafa8a5a7f
